management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  profiles:
    active: # json-logging
  application:
    name: spring-example
  cloud:
    function:
      definition: message-saver
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          message-saver-in-0:
            consumer:
              enable-dlq: true
      bindings:
        transaction-sender-out-0:
          destination: test-topic
        message-saver-in-0:
          destination: test-topic
          group: message-saver
