### health
GET http://127.0.0.1:8080/actuator/health HTTP/1.1

### readiness
GET http://127.0.0.1:8080/actuator/health/readiness HTTP/1.1

### liveness
GET http://127.0.0.1:8080/actuator/health/liveness HTTP/1.1

### metrics
GET http://127.0.0.1:8080/actuator/prometheus HTTP/1.1

### get messages
GET http://127.0.0.1:8080/messages HTTP/1.1

### new transaction
POST http://127.0.0.1:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "priority": 3,
    "accountNumber": "ACC-123456",
    "amount": 100,
    "description": "Test transaction"
}
