management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  profiles:
    active: json-logging
  application:
    name: spring-example
