name: Log into ECR
description: Logs into ECR

inputs:
  aws-region:
    required: true
    description: 'AWS region to deploy into'
  aws-role:
    required: true
    description: 'ARN of the role to push to ECR'

outputs:
  registry:
    value: ${{ steps.login-ecr.outputs.registry }}
    description: 'Docker registry'

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role }}
        mask-aws-account-id: false

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      #outputs: ${{ steps.login-ecr.outputs.registry }}
