management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1
  opentelemetry:
    resource-attributes:
        service.instance.id: ${random.uuid}
  otlp:
    tracing:
      endpoint: "http://localhost:4318/v1/traces"

spring:
  application:
    name: spring-webmvc
  main:
    banner-mode: off
  profiles:
    active: json-file-logging

logging.file.name: data/logs/${spring.application.name}.log

#otel:
#  java:
#    disabled:
#      resource:
#        providers:
#          - "io.opentelemetry.instrumentation.resources.ProcessResourceProvider"
