management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1 # tail-sampling in collector is preferred
  opentelemetry:
    resource-attributes:
      service.instance.id: ${random.uuid}
#  otlp:
#    tracing:
#      endpoint: "http://localhost:4318/v1/traces" # custom config below

otel:
  tracing:
    propagation:
#      strategy: "extracted,w3c,xray"
      extractStrategy: "extracted,w3c,xray"
      injectStrategy: "extracted,w3c"
  exporter:
    endpoint: "http://localhost:4317"

spring:
  application:
    name: spring-webmvc
  main:
    banner-mode: off
  profiles:
    active: json-file-logging

logging.file.name: data/logs/${spring.application.name}.log
