name: Build and push Docker image with Gradle
description: Logs into ECR, then builds, tags and pushes Docker image using Gradle

inputs:
  image-name:
    required: true
    description: 'Docker image name to build - in other words AWS repository name'

runs:
  using: composite
  steps:
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2

# Disable caching because it is not used by `gradle bootBuildImage`; TODO: revisit later maybe it can be made to work
# See also:
#   https://github.com/spring-projects/spring-boot/issues/28386
#   https://github.com/docker/build-push-action/issues/538
#
#
#    - name: Cache local Docker registry
#      uses: actions/cache@v3
#      with:
#        path: /tmp/docker-registry
#        key: docker-registry-${{ runner.os }}-${{ hashFiles(inputs.dockerfile) }}
#
#    - name: Run local Docker registry
#      shell: bash
#      run: >-
#        docker run
#        --detach
#        --publish 5000:5000
#        --restart=always
#        --name registry
#        --volume /tmp/docker-registry:/var/lib/registry
#        registry:2
#
#    - name: Pull image cache
#      shell: bash
#      run: >-
#        docker pull localhost:5000/${{ env.imageName }} &&
#        docker image tag localhost:5000/${{ env.imageName }} ${{ env.imageName }} || true

    - name: Build Docker image with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: ${{ env.WORKDIR }}
        arguments: >-
          bootBuildImage
          --imageName ${{ inputs.image-name }}

