management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

spring:
  profiles:
    active: # json-logging
  application:
    name: spring-example
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-example
    username: postgres
    password: postgres

spring.jpa.hibernate.ddl-auto: create
